### ISSUE TITLE
Converting database into a vector tile database

### ISSUE THREAD

**Issue by am2222** [rinigus/mapnik-styles-sqlite#9]
Hi,
I noticed converted data in spatilite faces a modest performance, So I thought that it would be good if we can convert data base into a vector tile format, There are some changes need be be done in input plugins for mapnik to render based on x,y,z but I have no idea about converting database into vector tile format. do you have any idea about this?does it make any changes at all?

**Comment by rinigus** [comment]
I have added support to Mapbox GL tiles by OSM Scout Server. Its a different format, hard to convert to (I have several projects running for making tiles and using them), but has fast rendering on the client. For making tiles, I am using PostGIS, not SQLite databases. You can use those probably, but there are few problems with it and conversion to MBTiles.

Its out of the scope for this project though, so I am going to close this as an issue :)

**Comment by am2222** [comment]
@rinigus  thanks very much for your reply, You mean you just queried from postsql database based on extent of each level and x,y? 
Can you help me about a good utility to make tiles based on x,y,z? I think here we can focuse on x,y as layers are fix in database and the z factor actuly is rendered by mapnik style. It could be possible to loop for each zoom level from 1 to 19 and then loop x,y extents (for example googles x,y,z) and clip data using database functions and save them, but I am looking for a proper of better method to make those tiles

**Comment by rinigus** [comment]
Its all quite tricky since data is stored/served differently. You would have to learn from docs how Mapbox GL tiles are stored (see mapbox site and others), test them (you could get tiles from openmaptiles.org as well as some description) and work with them. Understanding how it works will be sufficient to reply to your questions. For me, it took 1-2 months to learn internals and even more if you factor in writing scripts for importing them.

**Comment by am2222** [comment]
@rinigus  thanks very much for your help
